listener 1884 0.0.0.0
allow_anonymous true
persistence false

# listener 1884 0.0.0.0: broker MQTT aktif di port 1884 dan bisa diakses semua device 1 jaringan.
# allow_anonymous true: koneksi boleh tanpa login (khusus testing).
# persistence false: data pesan tidak disimpan permanen saat broker restart.



# listener 1884 0.0.0.0: “MQTT saya jalan di pintu nomor 1884, dan semua perangkat di WiFi boleh coba masuk.”
# allow_anonymous true: “Masuknya belum pakai username/password.”
# persistence false: “Kalau server MQTT dimatikan/di-restart, riwayat pesannya tidak disimpan.”
# Analogi:

# listener = nomor pintu
# allow_anonymous = perlu kartu identitas atau tidak
# persistence = catatan tamu disimpan atau tidak